FROM oven/bun:1

WORKDIR /app

COPY package.json bun.lock* ./
RUN bun install

COPY . .

# Exponemos el puerto por defecto de Angular
EXPOSE 4200

# Lanzamos ng serve permitiendo conexiones externas
CMD ["bun", "run", "start", "--", "--host", "0.0.0.0", "--poll", "2000"]
