import { IconName } from '../../interface/icons';

export const ICON_NAME_MAP: Record<IconName, string> = {
  html: 'HTML5',
  css: 'CSS3',
  js: 'JavaScript',
  ts: 'TypeScript',
  jquery: 'jQuery',
  bootstrap: 'Bootstrap',
  tailwind: 'Tailwind',
  angular: 'Angular',
  primeng: 'PrimeNG',
  ionic: 'Ionic',
  node: 'Node.js',
  express: 'Express',
  php: 'PHP',
  laravel: 'Laravel',
  codeigniter: 'CodeIgniter',
  mysql: 'MySQL',
  mongodb: 'MongoDB',
  sequelize: 'Sequelize',
  docker: 'Docker',
  xampp: 'XAMPP',
  laragon: 'Laragon',
  vscode: 'VS Code',
  postman: 'Postman',
  jest: 'Jest',
  jwt: 'JWT',
  github: 'GitHub',
  git: 'Git',
  clickup: 'ClickUp',
  penpot: 'Penpot',
  trello: 'Trello',
  udemy: 'Udemy',
  virtualbox: 'VirtualBox',
  debian: 'Debian',
  linux: 'Linux',
  json: 'JSON',
  electron: 'Electron',
  memory: 'Memoria RAM',
  cpu: 'CPU',
  gears: 'Configuración',
  tauri: 'Tauri',
  vitest: 'Vitest',
  postgresql: 'Postgresql',
  obsidian: 'Obsidian',
  figma: 'Figma',
  prisma: 'Prisma',
  dokploy: 'Dokploy',
  netlify: 'Netlify',
};
